#redis
spring:
  #添加数据库的配置
  datasource:
    url: jdbc:mysql://localhost/test?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  #redis的配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 20
      min-idle: 0
    timeout: 20

  # mybatis配置
  mybatis:
    # 配置映射类所在包名
    type-aliases-package: com.syc.boot.domain
    #开启MyBatis的二级缓存
    configuration:
      cache-enabled: true